#brew install texlive-fonts-recommended
#sudo tlmgr install CJKutf8
sudo tlmgr install adjustbox
sudo tlmgr install afterpage
sudo tlmgr install algorithm
sudo tlmgr install algorithm2e
sudo tlmgr install alltt
sudo tlmgr install amsmath
sudo tlmgr install amsthm
sudo tlmgr install arabtex
sudo tlmgr install atbegshi
sudo tlmgr install babel
sudo tlmgr install bera
sudo tlmgr install biblatex
sudo tlmgr install bigfoot
sudo tlmgr install binhex
sudo tlmgr install blindtext
sudo tlmgr install bookmark
sudo tlmgr install boxhandler
sudo tlmgr install caption
sudo tlmgr install ccicons
sudo tlmgr install changepage
sudo tlmgr install chngcntr
sudo tlmgr install cleveref
sudo tlmgr install collection-bibtexextra
sudo tlmgr install collection-binextra
sudo tlmgr install collection-latexextra
sudo tlmgr install color
sudo tlmgr install copyrightbox
sudo tlmgr install csquotes
sudo tlmgr install datatool
sudo tlmgr install datetime
sudo tlmgr install dblfloatfix
sudo tlmgr install enumerate
sudo tlmgr install enumitem
sudo tlmgr install etoc
sudo tlmgr install fancyvrb
sudo tlmgr install filehook
sudo tlmgr install float
sudo tlmgr install floatrow
sudo tlmgr install fontaxes
sudo tlmgr install footmisc
sudo tlmgr install footnote
sudo tlmgr install footnotebackref
sudo tlmgr install fouriernc
sudo tlmgr install fvextra
sudo tlmgr install glossaries
sudo tlmgr install hyphenat
sudo tlmgr install iflang
sudo tlmgr install ifmtarg
sudo tlmgr install ifoddpage
sudo tlmgr install ifpdf
sudo tlmgr install iftex
sudo tlmgr install import
sudo tlmgr install kao
sudo tlmgr install kastrup
sudo tlmgr install latexsym
sudo tlmgr install lettrine
sudo tlmgr install marginfix
sudo tlmgr install marginnote
sudo tlmgr install mathalfa
sudo tlmgr install mathalpha
sudo tlmgr install mathrsfs
sudo tlmgr install metalogo
sudo tlmgr install mfirstuc
sudo tlmgr install minitoc
sudo tlmgr install needspace
sudo tlmgr install newpx
sudo tlmgr install newpxmath
sudo tlmgr install newtx
sudo tlmgr install nextpage
sudo tlmgr install nomencl
sudo tlmgr install nth
sudo tlmgr install options
sudo tlmgr install outlines
sudo tlmgr install pdfpages
sudo tlmgr install pgf
sudo tlmgr install pgfgantt
sudo tlmgr install ragged2e
sudo tlmgr install relsize
sudo tlmgr install rotfloat
sudo tlmgr install scrlayer-scrpage
sudo tlmgr install setspace
sudo tlmgr install sidenotes
sudo tlmgr install silence
sudo tlmgr install snotez
sudo tlmgr install soul
sudo tlmgr install soul 
sudo tlmgr install subfig
sudo tlmgr install subfiles
sudo tlmgr install svg
sudo tlmgr install tabularx
sudo tlmgr install tcolorbox
sudo tlmgr install texlive-fonts-extra
sudo tlmgr install thmtools
sudo tlmgr install threeparttable
sudo tlmgr install tikz-cd
sudo tlmgr install tikzmark
sudo tlmgr install tikzpagenodes
sudo tlmgr install tlnet
sudo tlmgr install tocbasic
sudo tlmgr install trimspaces
sudo tlmgr install txfonts
sudo tlmgr install ulem
sudo tlmgr install unicode-math
sudo tlmgr install upgree
sudo tlmgr install upgreek
sudo tlmgr install url
sudo tlmgr install utf8
sudo tlmgr install verbatim
sudo tlmgr install wasysym
sudo tlmgr install wrapfig
sudo tlmgr install xfor
sudo tlmgr install xifthen
sudo tlmgr install xpatch
sudo tlmgr install xspace
sudo tlmgr install zref-abspage
tlmgr list --only-installed
